name: tf14

channels:
  - conda-forge
  - defaults

dependencies:
  - cudatoolkit=10.0
  - cudnn=7.6
  - cupti=10.0
  - mpi4py=3.0 # installs cuda-aware openmpi
  - nccl=2.4
  - pip=20.0
  - python=3.6
  - tensorflow-gpu=1.14 # installs tensorflow=2.1=gpu_py37h7a4bb67_0

